### ISSUE TITLE
Feature Request: Reload from file

### ISSUE THREAD

**Issue by ghost** [davvil/pdfpc#102]
Would it be possible to add an option to reload the pdf from disk while staying on the same slide? Something similar to vim's ``:e`` command. This could be usefull if one wants to use a slide for brainstorming or summarizing a discussion during some interactive part of the presentation.  Sort of like you sometimes do with a blackboard.

**Comment by mgkuhn** [comment]
Fixed in https://github.com/pdfpc/pdfpc/issues/409
