### ISSUE TITLE
Support for LaTeX Beamer notes

### ISSUE THREAD

**Issue by tobyS** [davvil/pdfpc#47]
Hi,

it would be awesome if there was support for notes as LaTeX Beamer creates them. It renders notes as dedicated slides directly after the actual slide they should be displayed for. I hope that these slides are annotated by Beamer in some way, so that PDFPC can detect them.

I rendered an example for you here: http://stuff.qafoo.com/minimal_example.pdf

Thanks in advance!

**Comment by bersace** [comment]
Hi, that would nice to support notes on seperate slides. It's the behaviour of 'notes' classoption of beamer. Anyone hint on this ?

**Comment by cebe** [comment]
@bersace this repository is not mainted anymore, you might want to look at https://github.com/pdfpc/pdfpc instead.

**Comment by bersace** [comment]
@cebe done, thanks
